# required to get an OSX environment
language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"

  # Get hold of ANT.
  - brew update
  - brew install ant

  # Grab Flex SDK
  - curl -L http://download.macromedia.com/pub/flex/sdk/flex_sdk_4.6.zip > flex_sdk.zip
  - unzip flex_sdk.zip -d ./flex_sdk
  - export "FLEX_HOME=`pwd`/flex_sdk"

  # Download and install a specific Flash Player from the Adobe Archives:
  # http://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html
  - curl -L https://raw.githubusercontent.com/Larusso/travis-CI-actionscript-demo/master/getFpFromArchive.sh > getFpFromArchive.sh
  - sh getFpFromArchive.sh 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_11.7.700.225_archive.zip'
  - export PATH="`pwd`/Flash Player Debugger.app/Contents/MacOS":$PATH

  - /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -v -f `pwd`/Flash Player Debugger.app

script: ant test

  # FLex-Mojo is expecting the "Flash Player" command so copy "Flash Player Debug" to "Flash Player"
  # - cp Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player